# Docker-compose file for testing via Github Actions
version: "3.1"
services:
  django:
    container_name: django-frontend
    build: .
    # Don't mount code for editing, in CI context
    # volumes: 
    # - .:/home/django/link-shortener
    ports: 
      - "8000:8000"
    env_file:
      - .docker-compose_django.env
      - .docker-compose_db.env
    depends_on:
      - db
  db:
    image: postgres:12
    env_file:
      - .docker-compose_db.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
