apiVersion: v1
kind: Service
metadata:
  name: {{ include "link-shortener.fullname" . }}
  namespace: link-shortener{{ .Values.django.env.run_env }}
  labels:
    {{- include "link-shortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.django.env.target_port | default "8000" }}
      protocol: TCP
      name: http
  selector:
    {{- include "link-shortener.selectorLabels" . | nindent 4 }}
