# Generated by Django 4.2.7 on 2024-01-05 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0002_link_shortlinks__short_p_179f6f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('query_string', models.CharField(blank=True)),
                ('referrer', models.CharField(blank=True)),
                ('user_agent', models.CharField(blank=True)),
                ('usage_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortlinks.link')),
            ],
        ),
    ]
